### ISSUE TITLE
Bundle web fonts as htmlDependency's

### ISSUE THREAD

**Issue by hadley** [lionel-/fontquiver#3]
To make it easy to use the web fonts inside RStudio/shiny/Rmarkdown etc.  Not worth a huge amount of time, but we should only bundle the web fonts if we do this too.

This would require creating a webfont style sheet for each font family, and setting up the correct call to `htmltools::htmlDependency()`

**Comment by lionel-** [comment]
I had a first pass at this function but it doesn't seem to work in my tests. I'm not really familiar with web tech and I don't have time to figure it out at the moment.

I generate the css file programmatically because that would be too much maintenance to write them by hand. The CSS file and all relevant fonts are copied to a temp directory. Also the usual advice on the matter is to include the ttf font as well. Or is there a specific reason to only include the web ones?

**Comment by hadley** [comment]
Do you have a test script handy? I think I've figured out what the problem is

**Comment by lionel-** [comment]
I used:

``` r
dep <- htmlFontDependency(style = "bold")
span <- htmltools::tags$span("test")
span_bold <- htmltools::tags$span(style = "font-family:fontquiver-bitstream-vera-sans-bold;", "test")
htmltools::div(span, span_bold, dep) %>% htmltools::html_print()
```

Also tested with a server to see if it's not due to restrictions on file:/// resources.

**Comment by hadley** [comment]
The use of a `tempdir()` isn't ideal because it'll be run multiple times if you have multiple chunks that use this dep (unless you cache it carefully). But there isn't a better way currently

**Comment by hadley** [comment]
htmltools issue: https://github.com/rstudio/htmltools/issues/67
